### ISSUE TITLE
"He" Does not work on OS X

### ISSUE THREAD

**Issue by Deviad** [mikelward/scripts#1]
Hello,
thank you for the he script.
Dunno if it is something that can be fixed easily but it does not work on OS X.
Thank you.

P.S.: does not work means that no output is being displayed whatsoever.

**Comment by mikelward** [comment]
Do you have `man` and `perl` installed?

What happens if you run it with `bash -x` in front, e.g. `bash -x he ls`?

**Comment by mikelward** [comment]
Let me know if you have more details. I don't have a macOS machine to test for myself.

**Comment by AllySummers** [comment]
Apologies for reviving an old thread. I believe the issue is to do with the BSD `man` utility that is installed on MacOS by default. I experienced the same issue with the default `man` utility as the issue creator had, but I do not experience the same issue after using `man-db` instead.
